# Generated by Django 4.2 on 2025-04-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='is_income',
            field=models.BooleanField(default=False, verbose_name='Тип пополнения'),
        ),
    ]
